### ISSUE TITLE
kudos geven aan mensen die hebben meegewerkt aan site

### ISSUE THREAD

**Issue by rouws** [cmdmethods/cmdmethods#25]
rijk, roos, ...

**Comment by rijkvanzanten** [comment]
🙋🏻‍♂️ 

Zijn PRs nog steeds welkom? :)

**Comment by rouws** [comment]
> 🙋🏻‍♂️
> 
> Zijn PRs nog steeds welkom? :)

JA :) van jou zeker!

**Comment by rouws** [comment]
Elke tip ben ik blij mee Rijk
